#!/usr/bin/env bash
# Build the Firefox variant of Repo Swap from the shared Chromium source.
#
# Layout (monorepo):
#   extension/
#   ├── chromium/        <- SINGLE SOURCE OF TRUTH (edit here)
#   ├── firefox/         <- generated by this script
#   └── build-firefox.sh <- you are here
#
# Shared assets (popup.html/css/js, icons) are copied from chromium/ into
# firefox/, and a Firefox-flavored manifest (gecko id) is written.
#
# Usage:  ./build-firefox.sh   (run from the extension/ folder)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$HERE/chromium"
OUT_DIR="$HERE/firefox"

mkdir -p "$OUT_DIR/icons"

# Copy shared assets (everything browser-agnostic)
cp "$SRC_DIR/popup.html" "$OUT_DIR/popup.html"
cp "$SRC_DIR/popup.css"  "$OUT_DIR/popup.css"
cp "$SRC_DIR/popup.js"   "$OUT_DIR/popup.js"
cp "$SRC_DIR/README.md"  "$OUT_DIR/README.md" 2>/dev/null || true
cp "$SRC_DIR"/icons/*.png "$OUT_DIR/icons/"
cp "$SRC_DIR"/icons/icon.svg "$OUT_DIR/icons/" 2>/dev/null || true

# Pull version from the Chromium manifest so the two stay aligned
VERSION="$(python3 -c "import json; print(json.load(open('$SRC_DIR/manifest.json'))['version'])")"

cat > "$OUT_DIR/manifest.json" <<JSON
{
  "manifest_version": 3,
  "name": "Repo Swap",
  "version": "$VERSION",
  "description": "Swap GitHub repository URLs into AI, diagram, wiki, dev environment, and repo-health tools.",
  "browser_specific_settings": {
    "gecko": {
      "id": "repo-swap@chrisradd.dev",
      "strict_min_version": "115.0",
      "data_collection_permissions": {
        "required": ["none"]
      }
    }
  },
  "permissions": ["tabs", "storage"],
  "host_permissions": ["https://github.com/*"],
  "icons": {
    "16": "icons/icon16.png",
    "32": "icons/icon32.png",
    "48": "icons/icon48.png",
    "128": "icons/icon128.png"
  },
  "action": {
    "default_title": "Repo Swap",
    "default_popup": "popup.html",
    "default_icon": {
      "16": "icons/icon16.png",
      "32": "icons/icon32.png",
      "48": "icons/icon48.png",
      "128": "icons/icon128.png"
    }
  }
}
JSON

echo "Firefox build written to: $OUT_DIR (version $VERSION)"
